
/* Drop Tables */

DROP TABLE LINECOMMENTS CASCADE CONSTRAINTS;
DROP TABLE ONEMEMO CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_LINECOMMENTS_LNO;
DROP SEQUENCE SEQ_ONEMEMO_NO;




/* Create Sequences */

CREATE SEQUENCE SEQ_LINECOMMENTS_LNO NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_ONEMEMO_NO NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE LINECOMMENTS
(
	LNO number NOT NULL,
	LINECOMMENT nvarchar2(50) NOT NULL,
	LPOSTDATE date DEFAULT SYSDATE,
	NO number NOT NULL,
	ID varchar2(20) NOT NULL,
	PRIMARY KEY (LNO)
);


CREATE TABLE MEMBERS
(
	ID varchar2(20) NOT NULL,
	PWD varchar2(10) NOT NULL,
	NAME nvarchar2(10),
	PRIMARY KEY (ID)
);


CREATE TABLE ONEMEMO
(
	NO number NOT NULL,
	TITLE nvarchar2(100) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	POSTDATE date DEFAULT SYSDATE,
	ID varchar2(20) NOT NULL,
	PRIMARY KEY (NO)
);



/* Create Foreign Keys */

ALTER TABLE LINECOMMENTS
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBERS (ID)
;


ALTER TABLE ONEMEMO
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBERS (ID)
;


ALTER TABLE LINECOMMENTS
	ADD FOREIGN KEY (NO)
	REFERENCES ONEMEMO (NO)
;

-- 샘플 데잍 
--INSERT INTO MEMBERS VALUES('KIM','1234','김길동');
--INSERT INTO MEMBERS VALUES('LEE','1234','이길동');
--INSERT INTO MEMBERS VALUES('PARK','1234','박길동');
--INSERT INTO MEMBERS VALUES('JEONG','1234','정길동');

